name: Publish

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: |
          npm ci
      - name: Semantic release
        run: npx semantic-release
